name: CI and build for the website

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 15
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run lint

  deploy: 
    needs: lint
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 15
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - run: npm ci
    - run: npm run build --if-present

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        allow_empty_commit: true
        publish_dir: ./public
        cname: komet.finance
